import JSZip from 'jszip';
import {
  FIRMWARE_DEVICE_PROFILE_ID,
  FIRMWARE_PACKAGE_SCHEMA_VERSION,
  FIRMWARE_TARGET,
  FIRMWARE_UPSTREAM_COMMIT,
  USB_HEADER_SOURCE_PATH,
  USB_LOGO_SOURCE_PATH,
  USB_PATCH_SOURCE_PATH,
  type FirmwarePackageFile,
  type FirmwarePackageManifest,
  type UsbFirmwareOptions,
  type UsbLogoInspection,
  type UsbLogoPosition
} from './types';

const textEncoder = new TextEncoder();
const ZIP_DATE = new Date('1980-01-01T00:00:00.000Z');

const readU16 = (bytes: Uint8Array, offset: number) =>
  bytes[offset] | (bytes[offset + 1] << 8);

const readU32 = (bytes: Uint8Array, offset: number) =>
  (bytes[offset] | (bytes[offset + 1] << 8) | (bytes[offset + 2] << 16) | (bytes[offset + 3] << 24)) >>> 0;

const readI32 = (bytes: Uint8Array, offset: number) => {
  const value = readU32(bytes, offset);
  return value > 0x7fffffff ? value - 0x100000000 : value;
};

export const inspectUsbLogoBmp = (bytes: Uint8Array): UsbLogoInspection => {
  if (bytes.byteLength < 54) return { valid: false, error: 'The BMP header is incomplete.' };
  if (bytes[0] !== 0x42 || bytes[1] !== 0x4d) return { valid: false, error: 'The file is not a Windows BMP.' };
  const fileSize = readU32(bytes, 2);
  const pixelOffset = readU32(bytes, 10);
  const dibSize = readU32(bytes, 14);
  const width = readI32(bytes, 18);
  const height = readI32(bytes, 22);
  const planes = readU16(bytes, 26);
  const bitsPerPixel = readU16(bytes, 28);
  const compression = readU32(bytes, 30);
  const rowBytes = Math.ceil((width * bitsPerPixel) / 32) * 4;
  const requiredBytes = pixelOffset + rowBytes * Math.abs(height);

  const details = { width, height, bitsPerPixel, compression };
  if (dibSize < 40) return { valid: false, ...details, error: 'Use a Windows BMP with a 40-byte or newer DIB header.' };
  if (width !== 176 || height !== 48) return { valid: false, ...details, error: 'The iPod Video USB logo must be exactly 176 × 48 pixels.' };
  if (planes !== 1) return { valid: false, ...details, error: 'The BMP must contain one image plane.' };
  if (bitsPerPixel !== 24) return { valid: false, ...details, error: 'Export the logo as an uncompressed 24-bit BMP.' };
  if (compression !== 0) return { valid: false, ...details, error: 'Compressed BMP files are not supported by the pinned Rockbox bitmap tool.' };
  if (fileSize > bytes.byteLength || requiredBytes > bytes.byteLength) {
    return { valid: false, ...details, error: 'The BMP pixel data is truncated.' };
  }
  return { valid: true, ...details };
};

export const createUsbScreenPatch = () => [
  `diff --git a/${USB_PATCH_SOURCE_PATH} b/${USB_PATCH_SOURCE_PATH}`,
  `--- a/${USB_PATCH_SOURCE_PATH}`,
  `+++ b/${USB_PATCH_SOURCE_PATH}`,
  '@@ -41,6 +41,7 @@',
  ' #include "icons.h"',
  ' ',
  ' #include "bitmaps/usblogo.h"',
  '+#include "rockbox_designer_usb.h"',
  ' ',
  ' #ifdef HAVE_REMOTE_LCD',
  ' #include "bitmaps/remote_usblogo.h"',
  '@@ -143,7 +144,8 @@ static void usb_screen_fix_viewports(struct screen *screen,',
  '         logo_height = parent->height;',
  ' ',
  '     *logo = *parent;',
  '-    logo->x = parent->x + parent->width - logo_width;',
  '+    logo->x = ROCKBOX_DESIGNER_USB_LOGO_X(',
  '+        parent->x, parent->width, logo_width);',
  ' #ifdef HAVE_LCD_SPLIT',
  '     switch (statusbar_position(screen))',
  '     {',
  ''
].join('\n');

const positionExpression: Record<UsbLogoPosition, string> = {
  left: '((parent_x))',
  center: '((parent_x) + (((parent_width) - (logo_width)) / 2))',
  right: '((parent_x) + ((parent_width) - (logo_width)))'
};

export const createUsbLayoutHeader = (position: UsbLogoPosition) => [
  '/* SPDX-License-Identifier: GPL-2.0-or-later */',
  '/* Generated by Rockbox Designer Firmware Mode. */',
  '#ifndef ROCKBOX_DESIGNER_USB_H',
  '#define ROCKBOX_DESIGNER_USB_H',
  '',
  `#define ROCKBOX_DESIGNER_USB_LOGO_X(parent_x, parent_width, logo_width) \\`,
  `    ${positionExpression[position]}`,
  '',
  '#endif /* ROCKBOX_DESIGNER_USB_H */',
  ''
].join('\n');

const normalizePackageName = (name: string) => name
  .trim()
  .toLowerCase()
  .replace(/[^a-z0-9]+/g, '-')
  .replace(/^-+|-+$/g, '')
  .slice(0, 64);

const sha256 = async (bytes: Uint8Array) => {
  const digest = await globalThis.crypto.subtle.digest('SHA-256', bytes as BufferSource);
  return [...new Uint8Array(digest)].map(value => value.toString(16).padStart(2, '0')).join('');
};

const addFile = async (
  zip: JSZip,
  files: FirmwarePackageFile[],
  path: string,
  content: string | Uint8Array,
  role: FirmwarePackageFile['role'],
  executable = false
) => {
  const bytes = typeof content === 'string' ? textEncoder.encode(content) : content;
  zip.file(path, bytes, {
    date: ZIP_DATE,
    createFolders: true,
    unixPermissions: executable ? 0o100755 : 0o100644
  });
  files.push({ path, bytes: bytes.byteLength, sha256: await sha256(bytes), role });
};

const createBuildScript = () => `#!/bin/sh
set -eu

PACKAGE_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
: "\${ROCKBOX_SOURCE_DIR:?Set ROCKBOX_SOURCE_DIR to a Rockbox Git checkout.}"
SOURCE_DIR=$(CDPATH= cd -- "$ROCKBOX_SOURCE_DIR" && pwd)
EXPECTED_SHA="${FIRMWARE_UPSTREAM_COMMIT}"
ACTUAL_SHA=$(git -C "$SOURCE_DIR" rev-parse HEAD)

if [ "$ACTUAL_SHA" != "$EXPECTED_SHA" ]; then
  echo "Refusing to build: Rockbox is $ACTUAL_SHA, expected $EXPECTED_SHA." >&2
  exit 2
fi

WORK_ROOT="\${ROCKBOX_FIRMWARE_WORK_DIR:-$PACKAGE_DIR/.work}"
SOURCE_WORK="$WORK_ROOT/source"
BUILD_DIR="$WORK_ROOT/build-ipodvideo"
OUTPUT_DIR="\${ROCKBOX_FIRMWARE_OUTPUT_DIR:-$PACKAGE_DIR/output}"

if [ -e "$SOURCE_WORK" ] || [ -e "$BUILD_DIR" ]; then
  echo "Refusing to replace an existing work directory: $WORK_ROOT" >&2
  exit 3
fi

mkdir -p "$WORK_ROOT" "$OUTPUT_DIR"
cleanup() {
  git -C "$SOURCE_DIR" worktree remove --force "$SOURCE_WORK" >/dev/null 2>&1 || true
}
trap cleanup EXIT INT TERM

git -C "$SOURCE_DIR" worktree add --detach "$SOURCE_WORK" "$EXPECTED_SHA"
git -C "$SOURCE_WORK" apply --check "$PACKAGE_DIR/patches/usb-screen-layout.patch"
git -C "$SOURCE_WORK" apply "$PACKAGE_DIR/patches/usb-screen-layout.patch"
cp "$PACKAGE_DIR/overlay/${USB_HEADER_SOURCE_PATH}" "$SOURCE_WORK/${USB_HEADER_SOURCE_PATH}"
cp "$PACKAGE_DIR/overlay/${USB_LOGO_SOURCE_PATH}" "$SOURCE_WORK/${USB_LOGO_SOURCE_PATH}"

mkdir -p "$BUILD_DIR"
set -- --target=${FIRMWARE_TARGET} --type=N --ram=64 --no-ccache
if [ -n "\${ROCKBOX_COMPILER_PREFIX:-}" ]; then
  set -- "$@" --compiler-prefix="$ROCKBOX_COMPILER_PREFIX"
fi
cd "$BUILD_DIR"
"$SOURCE_WORK/tools/configure" "$@" < /dev/null
make -C "$BUILD_DIR" -j"\${ROCKBOX_BUILD_JOBS:-4}" zip
cp "$BUILD_DIR/rockbox.ipod" "$OUTPUT_DIR/rockbox.ipod"
cp "$BUILD_DIR/rockbox.zip" "$OUTPUT_DIR/rockbox.zip"

echo "Built $OUTPUT_DIR/rockbox.ipod and $OUTPUT_DIR/rockbox.zip"
echo "Install only after following the recovery guidance in README.md."
`;

const createVerifyScript = () => `#!/bin/sh
set -eu

PACKAGE_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
: "\${ROCKBOX_SOURCE_DIR:?Set ROCKBOX_SOURCE_DIR to a Rockbox Git checkout.}"
EXPECTED_SHA="${FIRMWARE_UPSTREAM_COMMIT}"
ACTUAL_SHA=$(git -C "$ROCKBOX_SOURCE_DIR" rev-parse HEAD)

test "$ACTUAL_SHA" = "$EXPECTED_SHA" || {
  echo "Rockbox SHA mismatch: $ACTUAL_SHA (expected $EXPECTED_SHA)" >&2
  exit 2
}
git -C "$ROCKBOX_SOURCE_DIR" apply --check "$PACKAGE_DIR/patches/usb-screen-layout.patch"
echo "Patch check passed for ${FIRMWARE_TARGET} at $EXPECTED_SHA."
`;

const createReadme = (options: UsbFirmwareOptions) => `# ${options.packageName || 'Rockbox Designer'} — Firmware Assets USB fallback package

## Requires custom firmware

This is **not** a normal Rockbox theme ZIP. Ordinary themes author the connected-USB presentation in SBS at activity 21. This package changes only the compiled fallback logo and its placement for the Apple iPod Video 5G/5.5G target.

- Rockbox target: \`${FIRMWARE_TARGET}\`
- Required upstream revision: \`${FIRMWARE_UPSTREAM_COMMIT}\`
- USB logo placement: \`${options.logoPosition}\`
- Custom logo: \`${USB_LOGO_SOURCE_PATH}\` (176 × 48, 24-bit BMP)

## Before installing

1. Back up the iPod and confirm you can enter disk mode.
2. Keep a known-good official Rockbox build available for recovery.
3. Verify that the connected player is an iPod Video 5G/5.5G, not an iPod Classic.
4. Review the generated source patch and asset before building.

## Verify and build

Use a clean Git checkout of Rockbox at the exact SHA above. Install Rockbox's recommended \`arm-elf-eabi\` toolchain, then run:

\`\`\`sh
export ROCKBOX_SOURCE_DIR=/absolute/path/to/rockbox
./scripts/verify.sh
./scripts/build-ipodvideo.sh
\`\`\`

The build script creates a detached temporary worktree, applies the patch and overlay there, and writes \`rockbox.ipod\` plus \`rockbox.zip\` to \`output/\`. It does not modify the supplied checkout.

For a nonstandard compatible compiler, set \`ROCKBOX_COMPILER_PREFIX\` explicitly. Rockbox Designer's acceptance evidence records the compiler used.

## Licensing and distribution

The patch and generated C header are GPL-2.0-or-later. The logo remains the asset creator's responsibility. This package contains no Rockbox source tree, Rockbox binary, Apple firmware, or other proprietary firmware component. If you distribute a resulting modified Rockbox binary, you must satisfy the applicable GPL source and notice obligations.

The official Rockbox source remains authoritative. Firmware behavior is verified only for the target and revision above; hardware recovery is outside the browser editor.
`;

const createNotice = () => `Rockbox Designer Firmware Mode package

Patch and generated source overlay: SPDX-License-Identifier: GPL-2.0-or-later
Upstream Rockbox: https://git.rockbox.org/cgit/rockbox.git/
Required revision: ${FIRMWARE_UPSTREAM_COMMIT}

This archive does not contain a Rockbox source tree, a compiled Rockbox binary,
Apple firmware, or any other proprietary firmware component. The user-provided
bitmap remains subject to the asset creator's rights and permissions.
`;

export const createUsbFirmwarePackage = async (options: UsbFirmwareOptions) => {
  const inspection = inspectUsbLogoBmp(options.logoBmp);
  if (!inspection.valid) throw new Error(inspection.error ?? 'The USB logo BMP is invalid.');
  const packageName = normalizePackageName(options.packageName) || 'rockbox-designer-usb';
  const zip = new JSZip();
  const files: FirmwarePackageFile[] = [];

  await addFile(zip, files, 'patches/usb-screen-layout.patch', createUsbScreenPatch(), 'patch');
  await addFile(zip, files, `overlay/${USB_HEADER_SOURCE_PATH}`, createUsbLayoutHeader(options.logoPosition), 'source-overlay');
  await addFile(zip, files, `overlay/${USB_LOGO_SOURCE_PATH}`, options.logoBmp, 'target-asset');
  await addFile(zip, files, 'scripts/verify.sh', createVerifyScript(), 'build-script', true);
  await addFile(zip, files, 'scripts/build-ipodvideo.sh', createBuildScript(), 'build-script', true);
  await addFile(zip, files, 'README.md', createReadme({ ...options, packageName }), 'documentation');
  await addFile(zip, files, 'COPYING-NOTICE.txt', createNotice(), 'documentation');

  const manifest: FirmwarePackageManifest = {
    schemaVersion: FIRMWARE_PACKAGE_SCHEMA_VERSION,
    mode: 'firmware',
    feature: 'usb-fallback-logo',
    packageName,
    target: {
      deviceProfileId: FIRMWARE_DEVICE_PROFILE_ID,
      rockboxTarget: FIRMWARE_TARGET,
      upstreamCommit: FIRMWARE_UPSTREAM_COMMIT
    },
    output: {
      kind: 'source-patch-package',
      ordinaryThemeInstall: false,
      containsRockboxSourceTree: false,
      containsRockboxDerivedPatch: true,
      containsGeneratedGplSource: true,
      containsRockboxBinary: false,
      containsProprietaryFirmware: false
    },
    usbFallback: {
      logoPosition: options.logoPosition,
      logoAssetPath: USB_LOGO_SOURCE_PATH,
      logoWidth: 176,
      logoHeight: 48,
      logoBitsPerPixel: 24
    },
    files: [...files].sort((left, right) => left.path.localeCompare(right.path))
  };
  zip.file('manifest.json', `${JSON.stringify(manifest, null, 2)}\n`, {
    date: ZIP_DATE,
    createFolders: true,
    unixPermissions: 0o100644
  });

  const bytes = await zip.generateAsync({
    type: 'uint8array',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 },
    platform: 'UNIX'
  });
  return { bytes, filename: `${packageName}-firmware-${FIRMWARE_TARGET}.zip`, manifest };
};
