import { ProjectState, ElementType, TextElement, WpsElement, ImageElement, ScreenType } from '../types';

// Convert hex to Rockbox hex (strip #)
const toRbHex = (hex: string) => hex.replace('#', '');

/**
 * Compiles the visual ProjectState into a Rockbox .wps or .sbs file string.
 */
export const compileScreen = (project: ProjectState, screen: ScreenType): string => {
  const { elements, settings } = project;
  const safeName = settings.name.replace(/\s+/g, '_').toLowerCase();
  
  let code = `%wd\n`; // Clear display

  // 1. Background / Backdrop (Only for WPS usually, unless SBS has one)
  if (screen === 'wps' && settings.backdrop) {
      code += `%X|${safeName}_bg.bmp|\n`;
  }
  
  // 2. Viewports and Elements
  elements.filter(el => el.screen === screen).forEach(el => {
    if (!el.visible) return;

    // Viewport setup
    const fontIndex = '-'; 
    code += `\n# Element: ${el.name}\n`;
    code += `%V(${el.x},${el.y},${el.width},${el.height},${fontIndex})\n`;

    // Content
    switch (el.type) {
      case ElementType.RECT:
        code += `%Vf(${toRbHex(el.color)})\n`; 
        code += `%Cl(0,0,${el.width},${el.height},c,c)\n`; 
        break;

      case ElementType.TEXT:
        const textEl = el as TextElement;
        code += `%Vf(${toRbHex(textEl.color)})\n`;
        let alignTag = '%ac';
        if (textEl.align === 'left') alignTag = '%al';
        if (textEl.align === 'right') alignTag = '%ar';
        code += `${alignTag}${textEl.content}\n`;
        break;

      case ElementType.PROGRESS_BAR:
        code += `%Vf(${toRbHex((el as any).foreColor)})\n`;
        code += `%Vb(${toRbHex((el as any).backColor)})\n`;
        code += `%pb(0,0,${el.width},${el.height},-)\n`;
        break;
        
      case ElementType.IMAGE:
        const imgEl = el as ImageElement;
        if (imgEl.filename) {
             code += `%x|${safeName}_img/${imgEl.filename}|\n`;
        }
        break;
    }
  });

  return code;
};

export const compileWps = (project: ProjectState) => compileScreen(project, 'wps');
export const compileSbs = (project: ProjectState) => compileScreen(project, 'sbs');

/**
 * Generates the .cfg file
 */
export const compileCfg = (project: ProjectState): string => {
  const themeName = project.settings.name.replace(/\s+/g, '_').toLowerCase();
  return `# Generated by RamsBox IDE
wps: /.rockbox/wps/${themeName}.wps
sbs: /.rockbox/wps/${themeName}.sbs
font: /.rockbox/fonts/14-Nimbus.fnt
background color: ${toRbHex(project.settings.backgroundColor)}
statusbar: ${project.settings.statusBarTop ? 'top' : 'off'}
`;
};

/**
 * Helper to convert Base64 Data URL to Uint8Array (binary)
 */
function dataURItoBlob(dataURI: string): Blob {
    const byteString = atob(dataURI.split(',')[1]);
    const mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
    const ab = new ArrayBuffer(byteString.length);
    const ia = new Uint8Array(ab);
    for (let i = 0; i < byteString.length; i++) {
        ia[i] = byteString.charCodeAt(i);
    }
    return new Blob([ab], { type: mimeString });
}

/**
 * Generates the ZIP blob (Requires JSZip loaded in window)
 */
export const generateZip = async (project: ProjectState): Promise<Blob | null> => {
    // @ts-ignore
    if (typeof JSZip === 'undefined') {
        console.error("JSZip not loaded");
        return null;
    }

    // @ts-ignore
    const zip = new JSZip();
    const themeName = project.settings.name.replace(/\s+/g, '_').toLowerCase();
    const assetsFolder = `${themeName}_img`;

    // 1. Theme file
    zip.file(`.rockbox/themes/${themeName}.cfg`, compileCfg(project));

    // 2. WPS file
    zip.file(`.rockbox/wps/${themeName}.wps`, compileWps(project));
    
    // 3. SBS file
    zip.file(`.rockbox/wps/${themeName}.sbs`, compileSbs(project));

    // 4. Assets (Images layers)
    const imgFolder = zip.folder(`.rockbox/wps/${assetsFolder}`);
    if (imgFolder) {
        Object.keys(project.assets).forEach(filename => {
            const base64 = project.assets[filename];
            
            // Check if this is the backdrop
            if (filename === project.settings.backdrop) {
                zip.file(`.rockbox/wps/${themeName}_bg.bmp`, dataURItoBlob(base64)); 
            } else {
                imgFolder.file(filename, dataURItoBlob(base64));
            }
        });
    }

    // 5. Project Source (for reloading in the IDE)
    zip.file(`ramsbox_project.json`, JSON.stringify(project, null, 2));
    
    return await zip.generateAsync({ type: "blob" });
};
