import { ProjectState, ElementType, TextElement, WpsElement, ImageElement } from '../types';

// Convert hex to Rockbox hex (strip #)
const toRbHex = (hex: string) => hex.replace('#', '');

/**
 * Compiles the visual ProjectState into a Rockbox .wps file string.
 */
export const compileWps = (project: ProjectState): string => {
  const { elements, settings } = project;
  const safeName = settings.name.replace(/\s+/g, '_').toLowerCase();
  
  let wps = `%wd\n`; // Clear display

  // 1. Background / Backdrop
  // If a backdrop is set in settings, we load it efficiently using %X
  if (settings.backdrop) {
      wps += `%X|${safeName}_bg.bmp|\n`;
  } else {
      // If no image, we rely on the viewport clear color
      // But purely for safety in Rockbox, we might want to ensure the main viewport has the BG color
  }
  
  // 2. Viewports and Elements
  elements.forEach(el => {
    if (!el.visible) return;

    // Viewport setup for this element
    // %V(x,y,width,height,font)
    const fontIndex = (el.type === ElementType.TEXT) ? '-' : '-'; 
    wps += `\n# Element: ${el.name}\n`;
    wps += `%V(${el.x},${el.y},${el.width},${el.height},${fontIndex})\n`;

    // Content based on type
    switch (el.type) {
      case ElementType.RECT:
        wps += `%Vf(${toRbHex(el.color)})\n`; // Set FG color
        wps += `%Cl(0,0,${el.width},${el.height},c,c)\n`; // Clear rect with FG color (fill)
        break;

      case ElementType.TEXT:
        const textEl = el as TextElement;
        wps += `%Vf(${toRbHex(textEl.color)})\n`;
        // Alignment tags
        let alignTag = '%ac';
        if (textEl.align === 'left') alignTag = '%al';
        if (textEl.align === 'right') alignTag = '%ar';
        wps += `${alignTag}${textEl.content}\n`;
        break;

      case ElementType.PROGRESS_BAR:
        wps += `%Vf(${toRbHex((el as any).foreColor)})\n`;
        wps += `%Vb(${toRbHex((el as any).backColor)})\n`;
        wps += `%pb(0,0,${el.width},${el.height},-)\n`;
        break;
        
      case ElementType.IMAGE:
        // We assume images are placed in /.rockbox/wps/ThemeName_img/
        const imgEl = el as ImageElement;
        if (imgEl.filename) {
             wps += `%x|${safeName}_img/${imgEl.filename}|\n`;
        }
        break;
    }
  });

  return wps;
};

/**
 * Generates the .cfg file
 */
export const compileCfg = (project: ProjectState): string => {
  const themeName = project.settings.name.replace(/\s+/g, '_').toLowerCase();
  return `# Generated by RamsBox IDE
wps: /.rockbox/wps/${themeName}.wps
sbs: /.rockbox/wps/${themeName}.sbs
font: /.rockbox/fonts/14-Nimbus.fnt
background color: ${toRbHex(project.settings.backgroundColor)}
statusbar: ${project.settings.statusBarTop ? 'top' : 'off'}
`;
};

/**
 * Helper to convert Base64 Data URL to Uint8Array (binary)
 */
function dataURItoBlob(dataURI: string): Blob {
    const byteString = atob(dataURI.split(',')[1]);
    const mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
    const ab = new ArrayBuffer(byteString.length);
    const ia = new Uint8Array(ab);
    for (let i = 0; i < byteString.length; i++) {
        ia[i] = byteString.charCodeAt(i);
    }
    return new Blob([ab], { type: mimeString });
}

/**
 * Generates the ZIP blob (Requires JSZip loaded in window)
 */
export const generateZip = async (project: ProjectState): Promise<Blob | null> => {
    // @ts-ignore
    if (typeof JSZip === 'undefined') {
        console.error("JSZip not loaded");
        return null;
    }

    // @ts-ignore
    const zip = new JSZip();
    const themeName = project.settings.name.replace(/\s+/g, '_').toLowerCase();
    const assetsFolder = `${themeName}_img`;

    // 1. Theme file
    zip.file(`.rockbox/themes/${themeName}.cfg`, compileCfg(project));

    // 2. WPS file
    zip.file(`.rockbox/wps/${themeName}.wps`, compileWps(project));
    
    // 3. SBS file (Dummy for now)
    zip.file(`.rockbox/wps/${themeName}.sbs`, `%wd\n%V(0,0,320,16,-)\n%al%t %ar%bl%%`);

    // 4. Assets (Images layers)
    const imgFolder = zip.folder(`.rockbox/wps/${assetsFolder}`);
    if (imgFolder) {
        Object.keys(project.assets).forEach(filename => {
            // Check if this is the backdrop (stored as special key or just by name?)
            // We store backdrop in assets map too.
            const base64 = project.assets[filename];
            
            // Check if this is the main backdrop
            if (filename === project.settings.backdrop) {
                // Save at root wps folder as ThemeName_bg.bmp (assuming user provided BMP/compatible, or we just save raw)
                // Realistically Rockbox prefers BMP. Browsers give us PNG/JPEG base64. 
                // Conversion to BMP in JS is heavy, we'll save as uploaded for now and assume user knows or rockbox handles it (Rockbox does support bmp)
                zip.file(`.rockbox/wps/${themeName}_bg.bmp`, dataURItoBlob(base64)); 
            } else {
                imgFolder.file(filename, dataURItoBlob(base64));
            }
        });
    }

    // 5. Project Source (for reloading in the IDE)
    zip.file(`ramsbox_project.json`, JSON.stringify(project, null, 2));
    
    return await zip.generateAsync({ type: "blob" });
};
