import { ThemeConfig, LayoutStyle } from '../types';

/**
 * Helper to convert hex color to Rockbox hex format (FFFFFF)
 * Rockbox cfg uses 6-digit hex.
 */
const toHex = (color: string): string => color.replace('#', '');

export const generateThemeFiles = (config: ThemeConfig) => {
  const bg = toHex(config.colors.background);
  const fg = toHex(config.colors.foreground);
  const barBg = toHex(config.colors.barBackground);
  const barFg = toHex(config.colors.barForeground);

  // 1. Theme Configuration (.cfg)
  // This tells Rockbox which WPS/SBS files to load and sets global fonts/colors
  const cfgContent = `# Generated by RamsBox
# Theme: ${config.name}
# Platform: iPod Classic / 5G / Video (320x240)

wps: /.rockbox/wps/${config.name}.wps
sbs: /.rockbox/wps/${config.name}.sbs
font: /.rockbox/fonts/${config.font}
foreground color: ${fg}
background color: ${bg}
line selector start color: ${barBg}
line selector end color: ${barBg}
line selector text color: ${barFg}
statusbar: ${config.statusBar ? 'top' : 'off'}
scrollbar: right
backdrop: -
`;

  // 2. Status Bar Screen (.sbs)
  // Simple status bar with battery and volume
  const sbsContent = `%wd
# Clear screen
%X|${config.name}_bg.bmp|
%V(0,0,320,16,-)
%Vf(${fg})
%Vb(${bg})
%al%?mp<Stop|Play|Pause|Ffwd|Rew|Rec|Rec Pause|FM|FM Pause>  %ac%?cf<%cH:%cM|%cH:%cM>  %ar%bl%%  %?pv<%pv|%pv|%pv|%pv|Mute>
`;

  // 3. While Playing Screen (.wps)
  let wpsContent = `%wd\n`;
  
  const isSplit = config.layout === LayoutStyle.SPLIT;
  const isMinimal = config.layout === LayoutStyle.MINIMAL;

  // -- Album Art Viewport --
  if (config.showAlbumArt) {
     if (isMinimal) {
        // Left aligned small art
        wpsContent += `# Art - Minimal Layout
%V(10,30,100,100,-)
%Cl(0,0,100,100,c,c)
%Cd
`;
     } else if (isSplit) {
        // Top half art
         wpsContent += `# Art - Split Layout
%V(0,20,320,120,-)
%Cl(0,0,320,120,c,c)
%Cd
`;
     } else {
        // Full background art
        wpsContent += `# Art - Full Layout
%V(0,0,320,240,-)
%Cl(0,0,320,240,c,c)
%Cd
`;
     }
  }

  // -- Text Metadata Viewport --
  let textY = isSplit ? 150 : 30;
  let textX = (config.showAlbumArt && isMinimal) ? 120 : 10;
  let textW = (config.showAlbumArt && isMinimal) ? 190 : 300;
  let textH = 100;

  wpsContent += `# Metadata Area
%V(${textX},${textY},${textW},${textH},-)
%Vf(${fg})
%Vb(${bg})
%ac%s%?it<%| (Track %it)>
%ac%a
%ac%id
%ac%?Iy<%Iy|%ik>
`;

  // -- Progress Bar & Times Viewport --
  wpsContent += `# Progress Area
%V(10,210,300,30,-)
%Vf(${fg})
%Vb(${bg})
%ac%pc / %pt
# Custom Progress Bar (Simulated with simple pb)
%pb(0,14,300,6,-)
`;

  // -- Next Song (Peek) --
  if (config.showNextSong) {
      wpsContent += `# Next Song Peek
%V(10,190,300,16,-)
%Vf(${toHex(config.colors.accent)})
%Vb(${bg})
%alNEXT: %It
`;
  }

  return {
    cfg: cfgContent,
    sbs: sbsContent,
    wps: wpsContent
  };
};
